import React, {Component} from 'react';
import { Link } from 'react-router-dom';

class Terms extends Component {
    render() {
        return (
            <div className="main__terms">
                <div className="main__title"><h1>Terms and conditions</h1></div>
                    <p>1. Scope of validity <br />The Terms and Conditions apply to legal relations between patrons, on the one hand, and the Berlin City Hall Foundation, on the other, concerning the latter’s artistic establishments (Deutsche Oper Berlin, Staatsoper Unter den Linden, Komische Oper Berlin and Staatsballett Berlin). Where the following refers explicitly only to the Berlin City Hall Foundation, this also refers implicitly to its artistic establishments. The Terms and Conditions form part of the contract which comes into existence when tickets are purchased. The Terms and Conditions also apply to subscribers and patron organisations and their members, if not waived by a separate agreement.</p>
                    <p>2. Schedules and start times<br />The valid schedules and start times can be found in the official publications of the Berlin City Hall Foundation. The Berlin City Hall Foundation reserves the right to alter the schedules and casts. The Berlin City Hall Foundation accepts no responsibility for information on posters or other publications.</p>
                    <p>3. Entrance fee <br />The Berlin City Hall Foundation will publish the valid entrance fees and make them known at the ticket offices. Discounts are available to groups of persons with special entitlements, upon presentation of an appropriate certificate at the ticket office. Discounted tickets are valid only with this certificate. If the certificate cannot be produced, the difference between the discount fee and the full entrance fee must be paid in full.</p>
                    <p>4. Provision of tickets <br />Tickets will be sold in advance for a season at the times listed in the publications of the Berlin City Hall Foundation. The Berlin City Hall Foundation reserves the right to limit the number of tickets per buyer in individual cases. Severely disabled people can be given preferential treatment. Ticket orders in writing will be processed from the start of the advance sale period on a ‘first come, first served’ basis. There is, however, no right to have orders processed on this basis. Telephone ticket orders will be accepted from the start of the advance sale period. If payment for ordered tickets is not received within the stipulated time limit, these tickets will be made available for resale. Pre-paid tickets can be sent by post on request. Both the costs and the risks of sending them by post will be borne by the purchaser. Purchased entry tickets may not be resold for commercial purposes without the prior consent of the Berlin City Hall Foundation. If contravened, the Berlin City Hall Foundation reserves the right to legal recourse. Furthermore, the Foundation is entitled to refuse to sell entry tickets in future to those contravening the aforementioned prohibition. The Berlin City Hall Foundation reserves the right to alter or amend existing ticket sale regulations. They will be published and made known at the ticket offices by the Berlin City Hall Foundation.</p>
                    <p>5. Ticket refunds <br />Sold tickets will not be refunded, nor will compensation be paid for expired tickets, except in the cases listed below. The Berlin City Hall Foundation reserves the right to alter casts, and cast alterations do not entitle ticket holders to have their tickets refunded. If the work performed is different from that indicated when the ticket was purchased, the ticket can be returned before the beginning of the performance and the ticket price will be refunded. If a performance is cancelled without substitution, the ticket price will be refunded, as long as the tickets are presented or sent to Patron Services within 30 days of the scheduled date of the performance. If a performance is ended prematurely, patrons are entitled to have their tickets refunded only if the performance is ended before the first interval, or, if the performance does not have an interval, if it is ended before half of its scheduled duration has elapsed. Even in these cases, claims for refunds are valid only if the tickets are presented or sent to Patron Services within 30 days of the date of the performance. Apart from the right to have the entrance fee refunded, as provided in the above paragraphs, no other expenses or damages claimed by patrons will be paid.</p>
                    <p>6. Lost tickets <br />If a patron loses his or her ticket, he or she will be provided with a replacement ticket at the ticket office, as long as he or she gives a believable account of which ticket he or she has purchased. The holder of an original ticket takes precedence over the holder of a replacement ticket.</p>
                    <p>7. Entry <br />The audience cloakrooms and foyers are ordinarily opened one hour before the beginning of a performance. No one is entitled to enter after the performance has begun. If a patron is denied entry on account of his or her lateness, he or she has no right to have his or her ticket refunded.</p>
                    <p>8. Cloakroom <br />Objects and clothing carried by the guest, in particular backpacks, suitcases or larger bags have to be deposited at the cloakroom during the performance. Animals will categorically not be supervised. The Berlin City Hall Foundation reserves the right to charge a cloakroom fee. Coats left for supervision are insured in accordance with published insurance terms and conditions. Patrons of Deutsche Oper Berlin can leave furs for supervision only in designated cloakrooms for an insurance fee. Supervised property will be returned upon presentation of cloakroom tags without further proof of ownership. If no tag is presented, cloakroom items left for supervision will be returned only if the patron gives a believable account of his or her entitlement to the items. If the patron receives the wrong items, his or her items are damaged, or he or she has lost the cloakroom tag, this must be reported immediately to the cloakroom personnel. If a tag is lost, the patron is liable for replacement costs.</p>
                    <p>9. Lost property <br />Lost property of any description found in the performance venues of the Berlin City Hall Foundation must be handed in to the house or cloakroom personnel. Lost property will be dealt with in accordance with the provisions of §§ 978ff. of the German Civil Code.</p>
                <div className="main__button"><button onClick={() => {
                    return <Link to={`${window.history.back()}`}/>
                }}>Return</button></div>

            </div>
        );
    }
}

export default Terms;